<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20261007082253 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT AUTO_INCREMENT NOT NULL, body LONGTEXT NOT NULL, headers LONGTEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at DATETIME NOT NULL, available_at DATETIME NOT NULL, delivered_at DATETIME DEFAULT NULL, INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 (queue_name, available_at, delivered_at, id), PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE passkeys DROP FOREIGN KEY `passkeys_user_id_foreign`');
        $this->addSql('ALTER TABLE pending_checkouts DROP FOREIGN KEY `pending_checkouts_customer_address_id_foreign`');
        $this->addSql('ALTER TABLE pending_checkouts DROP FOREIGN KEY `pending_checkouts_customer_id_foreign`');
        $this->addSql('ALTER TABLE pending_checkouts DROP FOREIGN KEY `pending_checkouts_order_id_foreign`');
        $this->addSql('ALTER TABLE pending_checkouts DROP FOREIGN KEY `pending_checkouts_restaurant_id_foreign`');
        $this->addSql('DROP TABLE cache');
        $this->addSql('DROP TABLE cache_locks');
        $this->addSql('DROP TABLE failed_jobs');
        $this->addSql('DROP TABLE jobs');
        $this->addSql('DROP TABLE job_batches');
        $this->addSql('DROP TABLE passkeys');
        $this->addSql('DROP TABLE password_reset_tokens');
        $this->addSql('DROP TABLE pending_checkouts');
        $this->addSql('DROP TABLE sessions');
        $this->addSql('ALTER TABLE admins DROP FOREIGN KEY `admins_user_id_foreign`');
        $this->addSql('ALTER TABLE admins ADD CONSTRAINT FK_A2E0150FA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT');
        $this->addSql('ALTER TABLE conversations DROP FOREIGN KEY `conversations_order_id_foreign`');
        $this->addSql('ALTER TABLE conversations CHANGE type type VARCHAR(32) NOT NULL');
        $this->addSql('ALTER TABLE conversations ADD CONSTRAINT FK_C2521BF18D9F6D38 FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE RESTRICT');
        $this->addSql('ALTER TABLE customer_addresses DROP FOREIGN KEY `customer_addresses_customer_id_foreign`');
        $this->addSql('ALTER TABLE customer_addresses CHANGE delivery_instructions delivery_instructions TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE customer_addresses ADD CONSTRAINT FK_C4378D0C9395C3F3 FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE RESTRICT');
        $this->addSql('ALTER TABLE customers DROP FOREIGN KEY `customers_user_id_foreign`');
        $this->addSql('ALTER TABLE customers ADD CONSTRAINT FK_62534E21A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT');
        $this->addSql('ALTER TABLE menu_categories DROP FOREIGN KEY `menu_categories_restaurant_id_foreign`');
        $this->addSql('ALTER TABLE menu_categories ADD CONSTRAINT FK_1B5EF2BAB1E7706E FOREIGN KEY (restaurant_id) REFERENCES restaurants (id) ON DELETE RESTRICT');
        $this->addSql('ALTER TABLE menu_item_addons DROP FOREIGN KEY `menu_item_addons_menu_item_id_foreign`');
        $this->addSql('ALTER TABLE menu_item_addons ADD CONSTRAINT FK_35604DB49AB44FE0 FOREIGN KEY (menu_item_id) REFERENCES menu_items (id) ON DELETE RESTRICT');
        $this->addSql('ALTER TABLE menu_item_variants DROP FOREIGN KEY `menu_item_variants_menu_item_id_foreign`');
        $this->addSql('ALTER TABLE menu_item_variants ADD CONSTRAINT FK_7956CEBC9AB44FE0 FOREIGN KEY (menu_item_id) REFERENCES menu_items (id) ON DELETE RESTRICT');
        $this->addSql('ALTER TABLE menu_items DROP FOREIGN KEY `menu_items_menu_category_id_foreign`');
        $this->addSql('ALTER TABLE menu_items CHANGE description description TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE menu_items ADD CONSTRAINT FK_70B2CA2A7ABA83AE FOREIGN KEY (menu_category_id) REFERENCES menu_categories (id) ON DELETE RESTRICT');
        $this->addSql('ALTER TABLE messages DROP FOREIGN KEY `messages_conversation_id_foreign`');
        $this->addSql('ALTER TABLE messages DROP FOREIGN KEY `messages_sender_user_id_foreign`');
        $this->addSql('ALTER TABLE messages CHANGE body body TEXT NOT NULL');
        $this->addSql('ALTER TABLE messages ADD CONSTRAINT FK_DB021E969AC0396 FOREIGN KEY (conversation_id) REFERENCES conversations (id) ON DELETE RESTRICT');
        $this->addSql('ALTER TABLE messages ADD CONSTRAINT FK_DB021E962A98155E FOREIGN KEY (sender_user_id) REFERENCES users (id) ON DELETE RESTRICT');
        $this->addSql('ALTER TABLE notifications DROP FOREIGN KEY `notifications_user_id_foreign`');
        $this->addSql('ALTER TABLE notifications CHANGE body body TEXT NOT NULL');
        $this->addSql('ALTER TABLE notifications ADD CONSTRAINT FK_6000B0D3A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT');
        $this->addSql('ALTER TABLE order_item_addons DROP FOREIGN KEY `order_item_addons_order_item_id_foreign`');
        $this->addSql('ALTER TABLE order_item_addons ADD CONSTRAINT FK_462E2C7EE415FB15 FOREIGN KEY (order_item_id) REFERENCES order_items (id) ON DELETE RESTRICT');
        $this->addSql('ALTER TABLE order_items DROP FOREIGN KEY `order_items_order_id_foreign`');
        $this->addSql('ALTER TABLE order_items CHANGE special_instructions special_instructions TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE order_items ADD CONSTRAINT FK_62809DB08D9F6D38 FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE RESTRICT');
        $this->addSql('ALTER TABLE order_reports DROP FOREIGN KEY `order_reports_order_id_foreign`');
        $this->addSql('ALTER TABLE order_reports DROP FOREIGN KEY `order_reports_reported_by_user_id_foreign`');
        $this->addSql('ALTER TABLE order_reports CHANGE against against VARCHAR(16) NOT NULL, CHANGE type type VARCHAR(32) NOT NULL, CHANGE description description TEXT NOT NULL, CHANGE status status VARCHAR(32) DEFAULT \'open\' NOT NULL, CHANGE resolution resolution TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE order_reports ADD CONSTRAINT FK_7650E0E8D9F6D38 FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE RESTRICT');
        $this->addSql('ALTER TABLE order_reports ADD CONSTRAINT FK_7650E0EB79DEF28 FOREIGN KEY (reported_by_user_id) REFERENCES users (id) ON DELETE RESTRICT');
        $this->addSql('ALTER TABLE order_status_history DROP FOREIGN KEY `order_status_history_order_id_foreign`');
        $this->addSql('ALTER TABLE order_status_history CHANGE changed_by changed_by VARCHAR(32) NOT NULL, CHANGE note note TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE order_status_history ADD CONSTRAINT FK_471AD77E8D9F6D38 FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE RESTRICT');
        $this->addSql('ALTER TABLE orders DROP FOREIGN KEY `orders_customer_id_foreign`');
        $this->addSql('ALTER TABLE orders DROP FOREIGN KEY `orders_restaurant_id_foreign`');
        $this->addSql('ALTER TABLE orders DROP FOREIGN KEY `orders_rider_id_foreign`');
        $this->addSql('ALTER TABLE orders CHANGE status status VARCHAR(64) DEFAULT \'placed\' NOT NULL, CHANGE payment_method payment_method VARCHAR(16) NOT NULL, CHANGE customer_notes customer_notes TEXT DEFAULT NULL, CHANGE rejection_reason rejection_reason TEXT DEFAULT NULL, CHANGE cancellation_reason cancellation_reason TEXT DEFAULT NULL, CHANGE cancelled_by cancelled_by VARCHAR(32) DEFAULT NULL');
        $this->addSql('ALTER TABLE orders ADD CONSTRAINT FK_E52FFDEE9395C3F3 FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE RESTRICT');
        $this->addSql('ALTER TABLE orders ADD CONSTRAINT FK_E52FFDEEB1E7706E FOREIGN KEY (restaurant_id) REFERENCES restaurants (id) ON DELETE RESTRICT');
        $this->addSql('ALTER TABLE orders ADD CONSTRAINT FK_E52FFDEEFF881F6 FOREIGN KEY (rider_id) REFERENCES riders (id) ON DELETE RESTRICT');
        $this->addSql('ALTER TABLE payment_status_history DROP FOREIGN KEY `payment_status_history_payment_id_foreign`');
        $this->addSql('ALTER TABLE payment_status_history CHANGE from_status from_status VARCHAR(32) DEFAULT NULL, CHANGE to_status to_status VARCHAR(32) NOT NULL, CHANGE changed_by changed_by VARCHAR(16) NOT NULL, CHANGE note note TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE payment_status_history ADD CONSTRAINT FK_CA42BDCA4C3A3BB FOREIGN KEY (payment_id) REFERENCES payments (id) ON DELETE RESTRICT');
        $this->addSql('ALTER TABLE payments DROP FOREIGN KEY `payments_order_id_foreign`');
        $this->addSql('ALTER TABLE payments CHANGE method method VARCHAR(16) NOT NULL, CHANGE status status VARCHAR(32) DEFAULT \'pending\' NOT NULL');
        $this->addSql('ALTER TABLE payments ADD CONSTRAINT FK_65D29B328D9F6D38 FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE RESTRICT');
        $this->addSql('ALTER TABLE restaurant_documents CHANGE type type VARCHAR(32) NOT NULL, CHANGE status status VARCHAR(32) DEFAULT \'pending\' NOT NULL, CHANGE rejection_reason rejection_reason TEXT DEFAULT NULL');
        $this->addSql('CREATE UNIQUE INDEX restaurant_documents_restaurant_type_unique ON restaurant_documents (restaurant_id, type)');
        $this->addSql('ALTER TABLE restaurant_operating_hours CHANGE day_of_week day_of_week TINYINT UNSIGNED NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX restaurant_operating_hours_restaurant_day_unique ON restaurant_operating_hours (restaurant_id, day_of_week)');
        $this->addSql('ALTER TABLE restaurant_payouts DROP FOREIGN KEY `restaurant_payouts_restaurant_id_foreign`');
        $this->addSql('ALTER TABLE restaurant_payouts CHANGE status status VARCHAR(16) DEFAULT \'pending\' NOT NULL');
        $this->addSql('ALTER TABLE restaurant_payouts ADD CONSTRAINT FK_3F05DCFBB1E7706E FOREIGN KEY (restaurant_id) REFERENCES restaurants (id) ON DELETE RESTRICT');
        $this->addSql('ALTER TABLE restaurant_reviews DROP FOREIGN KEY `restaurant_reviews_customer_id_foreign`');
        $this->addSql('ALTER TABLE restaurant_reviews DROP FOREIGN KEY `restaurant_reviews_order_id_foreign`');
        $this->addSql('ALTER TABLE restaurant_reviews DROP FOREIGN KEY `restaurant_reviews_restaurant_id_foreign`');
        $this->addSql('ALTER TABLE restaurant_reviews CHANGE rating rating TINYINT UNSIGNED NOT NULL, CHANGE comment comment TEXT DEFAULT NULL, CHANGE restaurant_reply restaurant_reply TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE restaurant_reviews ADD CONSTRAINT FK_A33BB77A8D9F6D38 FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE RESTRICT');
        $this->addSql('ALTER TABLE restaurant_reviews ADD CONSTRAINT FK_A33BB77A9395C3F3 FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE RESTRICT');
        $this->addSql('ALTER TABLE restaurant_reviews ADD CONSTRAINT FK_A33BB77AB1E7706E FOREIGN KEY (restaurant_id) REFERENCES restaurants (id) ON DELETE RESTRICT');
        $this->addSql('ALTER TABLE restaurants DROP FOREIGN KEY `restaurants_user_id_foreign`');
        $this->addSql('ALTER TABLE restaurants CHANGE description description TEXT DEFAULT NULL, CHANGE approval_status approval_status VARCHAR(32) DEFAULT \'pending\' NOT NULL, CHANGE rejection_reason rejection_reason TEXT DEFAULT NULL, CHANGE operating_status operating_status VARCHAR(32) DEFAULT \'closed\' NOT NULL, CHANGE payout_method payout_method VARCHAR(32) DEFAULT NULL');
        $this->addSql('ALTER TABLE restaurants ADD CONSTRAINT FK_AD837724A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT');
        $this->addSql('ALTER TABLE rider_cash_remittances DROP FOREIGN KEY `rider_cash_remittances_rider_id_foreign`');
        $this->addSql('ALTER TABLE rider_cash_remittances CHANGE status status VARCHAR(16) DEFAULT \'pending\' NOT NULL');
        $this->addSql('ALTER TABLE rider_cash_remittances ADD CONSTRAINT FK_38E5F645FF881F6 FOREIGN KEY (rider_id) REFERENCES riders (id) ON DELETE RESTRICT');
        $this->addSql('ALTER TABLE rider_documents CHANGE type type VARCHAR(32) NOT NULL, CHANGE status status VARCHAR(32) DEFAULT \'pending\' NOT NULL, CHANGE rejection_reason rejection_reason TEXT DEFAULT NULL');
        $this->addSql('CREATE UNIQUE INDEX rider_documents_rider_type_unique ON rider_documents (rider_id, type)');
        $this->addSql('ALTER TABLE rider_earnings DROP FOREIGN KEY `rider_earnings_order_id_foreign`');
        $this->addSql('ALTER TABLE rider_earnings DROP FOREIGN KEY `rider_earnings_rider_id_foreign`');
        $this->addSql('ALTER TABLE rider_earnings ADD CONSTRAINT FK_34A967BBFF881F6 FOREIGN KEY (rider_id) REFERENCES riders (id) ON DELETE RESTRICT');
        $this->addSql('ALTER TABLE rider_earnings ADD CONSTRAINT FK_34A967BB8D9F6D38 FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE RESTRICT');
        $this->addSql('ALTER TABLE rider_payouts DROP FOREIGN KEY `rider_payouts_rider_id_foreign`');
        $this->addSql('ALTER TABLE rider_payouts CHANGE status status VARCHAR(16) DEFAULT \'pending\' NOT NULL');
        $this->addSql('ALTER TABLE rider_payouts ADD CONSTRAINT FK_8D95A693FF881F6 FOREIGN KEY (rider_id) REFERENCES riders (id) ON DELETE RESTRICT');
        $this->addSql('ALTER TABLE rider_pool_declines DROP FOREIGN KEY `rider_pool_declines_order_id_foreign`');
        $this->addSql('ALTER TABLE rider_pool_declines DROP FOREIGN KEY `rider_pool_declines_rider_id_foreign`');
        $this->addSql('ALTER TABLE rider_pool_declines CHANGE action action VARCHAR(16) NOT NULL');
        $this->addSql('ALTER TABLE rider_pool_declines ADD CONSTRAINT FK_9A48C6358D9F6D38 FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE RESTRICT');
        $this->addSql('ALTER TABLE rider_pool_declines ADD CONSTRAINT FK_9A48C635FF881F6 FOREIGN KEY (rider_id) REFERENCES riders (id) ON DELETE RESTRICT');
        $this->addSql('CREATE UNIQUE INDEX rider_pool_declines_order_rider_unique ON rider_pool_declines (order_id, rider_id)');
        $this->addSql('ALTER TABLE rider_pool_offers CHANGE escalation_stage escalation_stage VARCHAR(32) DEFAULT \'initial\' NOT NULL');
        $this->addSql('ALTER TABLE rider_reviews DROP FOREIGN KEY `rider_reviews_customer_id_foreign`');
        $this->addSql('ALTER TABLE rider_reviews DROP FOREIGN KEY `rider_reviews_order_id_foreign`');
        $this->addSql('ALTER TABLE rider_reviews DROP FOREIGN KEY `rider_reviews_rider_id_foreign`');
        $this->addSql('ALTER TABLE rider_reviews CHANGE rating rating TINYINT UNSIGNED NOT NULL, CHANGE comment comment TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE rider_reviews ADD CONSTRAINT FK_11ABCD128D9F6D38 FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE RESTRICT');
        $this->addSql('ALTER TABLE rider_reviews ADD CONSTRAINT FK_11ABCD129395C3F3 FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE RESTRICT');
        $this->addSql('ALTER TABLE rider_reviews ADD CONSTRAINT FK_11ABCD12FF881F6 FOREIGN KEY (rider_id) REFERENCES riders (id) ON DELETE RESTRICT');
        $this->addSql('ALTER TABLE riders DROP FOREIGN KEY `riders_user_id_foreign`');
        $this->addSql('ALTER TABLE riders CHANGE vehicle_type vehicle_type VARCHAR(32) NOT NULL, CHANGE approval_status approval_status VARCHAR(32) DEFAULT \'pending\' NOT NULL, CHANGE rejection_reason rejection_reason TEXT DEFAULT NULL, CHANGE availability_status availability_status VARCHAR(32) DEFAULT \'offline\' NOT NULL, CHANGE payout_method payout_method VARCHAR(32) DEFAULT NULL');
        $this->addSql('ALTER TABLE riders ADD CONSTRAINT FK_4D574A38A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT');
        $this->addSql('ALTER TABLE support_tickets DROP FOREIGN KEY `support_tickets_user_id_foreign`');
        $this->addSql('ALTER TABLE support_tickets CHANGE message message TEXT NOT NULL, CHANGE status status VARCHAR(16) DEFAULT \'open\' NOT NULL');
        $this->addSql('ALTER TABLE support_tickets ADD CONSTRAINT FK_E9739508A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT');
        $this->addSql('ALTER TABLE users CHANGE two_factor_secret two_factor_secret TEXT DEFAULT NULL, CHANGE two_factor_recovery_codes two_factor_recovery_codes TEXT DEFAULT NULL, CHANGE role role VARCHAR(32) NOT NULL, CHANGE status status VARCHAR(32) DEFAULT \'active\' NOT NULL');
        $this->addSql('ALTER TABLE voucher_redemptions DROP FOREIGN KEY `voucher_redemptions_customer_id_foreign`');
        $this->addSql('ALTER TABLE voucher_redemptions DROP FOREIGN KEY `voucher_redemptions_order_id_foreign`');
        $this->addSql('ALTER TABLE voucher_redemptions DROP FOREIGN KEY `voucher_redemptions_voucher_id_foreign`');
        $this->addSql('ALTER TABLE voucher_redemptions ADD CONSTRAINT FK_6D711ECB28AA1B6F FOREIGN KEY (voucher_id) REFERENCES vouchers (id) ON DELETE RESTRICT');
        $this->addSql('ALTER TABLE voucher_redemptions ADD CONSTRAINT FK_6D711ECB8D9F6D38 FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE RESTRICT');
        $this->addSql('ALTER TABLE voucher_redemptions ADD CONSTRAINT FK_6D711ECB9395C3F3 FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE RESTRICT');
        $this->addSql('ALTER TABLE vouchers DROP FOREIGN KEY `vouchers_restaurant_id_foreign`');
        $this->addSql('ALTER TABLE vouchers CHANGE scope scope VARCHAR(16) NOT NULL, CHANGE type type VARCHAR(32) NOT NULL');
        $this->addSql('ALTER TABLE vouchers ADD CONSTRAINT FK_93150748B1E7706E FOREIGN KEY (restaurant_id) REFERENCES restaurants (id) ON DELETE RESTRICT');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE cache (`key` VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, value MEDIUMTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, expiration BIGINT NOT NULL, INDEX cache_expiration_index (expiration), PRIMARY KEY (`key`)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE cache_locks (`key` VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, owner VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, expiration BIGINT NOT NULL, INDEX cache_locks_expiration_index (expiration), PRIMARY KEY (`key`)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE failed_jobs (id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, uuid VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, connection VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, queue VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, payload LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, exception LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, failed_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, INDEX failed_jobs_connection_queue_failed_at_index (connection, queue, failed_at), UNIQUE INDEX failed_jobs_uuid_unique (uuid), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE jobs (id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, queue VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, payload LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, attempts SMALLINT UNSIGNED NOT NULL, reserved_at INT UNSIGNED DEFAULT NULL, available_at INT UNSIGNED NOT NULL, created_at INT UNSIGNED NOT NULL, INDEX jobs_queue_index (queue), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE job_batches (id VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, name VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, total_jobs INT NOT NULL, pending_jobs INT NOT NULL, failed_jobs INT NOT NULL, failed_job_ids LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, options MEDIUMTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, cancelled_at INT DEFAULT NULL, created_at INT NOT NULL, finished_at INT DEFAULT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE passkeys (id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, user_id BIGINT UNSIGNED NOT NULL, name VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, credential_id VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, credential JSON NOT NULL, last_used_at DATETIME DEFAULT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, UNIQUE INDEX passkeys_credential_id_unique (credential_id), INDEX passkeys_user_id_index (user_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE password_reset_tokens (email VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, token VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, created_at DATETIME DEFAULT NULL, PRIMARY KEY (email)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE pending_checkouts (id CHAR(36) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, idempotency_token CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, customer_id BIGINT UNSIGNED NOT NULL, restaurant_id BIGINT UNSIGNED NOT NULL, customer_address_id BIGINT UNSIGNED NOT NULL, payment_method ENUM(\'gcash\', \'card\') CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, payload JSON NOT NULL, total_amount NUMERIC(8, 2) NOT NULL, paymongo_session_id VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, paymongo_checkout_url TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, paymongo_reference VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, status ENUM(\'pending\', \'paid\', \'failed\', \'cancelled\') CHARACTER SET utf8mb4 DEFAULT \'pending\' NOT NULL COLLATE `utf8mb4_unicode_ci`, order_id BIGINT UNSIGNED DEFAULT NULL, expires_at DATETIME DEFAULT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, INDEX pending_checkouts_customer_address_id_foreign (customer_address_id), INDEX pending_checkouts_customer_id_status_index (customer_id, status), UNIQUE INDEX pending_checkouts_idempotency_token_unique (idempotency_token), UNIQUE INDEX pending_checkouts_order_id_unique (order_id), UNIQUE INDEX pending_checkouts_paymongo_reference_unique (paymongo_reference), UNIQUE INDEX pending_checkouts_paymongo_session_id_unique (paymongo_session_id), INDEX pending_checkouts_restaurant_id_foreign (restaurant_id), INDEX IDX_C1468C3A9395C3F3 (customer_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE sessions (id VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, user_id BIGINT UNSIGNED DEFAULT NULL, ip_address VARCHAR(45) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, user_agent TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, payload LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, last_activity INT NOT NULL, INDEX sessions_last_activity_index (last_activity), INDEX sessions_user_id_index (user_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('ALTER TABLE passkeys ADD CONSTRAINT `passkeys_user_id_foreign` FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pending_checkouts ADD CONSTRAINT `pending_checkouts_customer_address_id_foreign` FOREIGN KEY (customer_address_id) REFERENCES customer_addresses (id)');
        $this->addSql('ALTER TABLE pending_checkouts ADD CONSTRAINT `pending_checkouts_customer_id_foreign` FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pending_checkouts ADD CONSTRAINT `pending_checkouts_order_id_foreign` FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE pending_checkouts ADD CONSTRAINT `pending_checkouts_restaurant_id_foreign` FOREIGN KEY (restaurant_id) REFERENCES restaurants (id) ON DELETE CASCADE');
        $this->addSql('DROP TABLE messenger_messages');
        $this->addSql('ALTER TABLE admins DROP FOREIGN KEY FK_A2E0150FA76ED395');
        $this->addSql('ALTER TABLE admins ADD CONSTRAINT `admins_user_id_foreign` FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE conversations DROP FOREIGN KEY FK_C2521BF18D9F6D38');
        $this->addSql('ALTER TABLE conversations CHANGE type type ENUM(\'customer_rider\', \'customer_restaurant\') NOT NULL');
        $this->addSql('ALTER TABLE conversations ADD CONSTRAINT `conversations_order_id_foreign` FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE customers DROP FOREIGN KEY FK_62534E21A76ED395');
        $this->addSql('ALTER TABLE customers ADD CONSTRAINT `customers_user_id_foreign` FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE customer_addresses DROP FOREIGN KEY FK_C4378D0C9395C3F3');
        $this->addSql('ALTER TABLE customer_addresses CHANGE delivery_instructions delivery_instructions TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE customer_addresses ADD CONSTRAINT `customer_addresses_customer_id_foreign` FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE menu_categories DROP FOREIGN KEY FK_1B5EF2BAB1E7706E');
        $this->addSql('ALTER TABLE menu_categories ADD CONSTRAINT `menu_categories_restaurant_id_foreign` FOREIGN KEY (restaurant_id) REFERENCES restaurants (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE menu_items DROP FOREIGN KEY FK_70B2CA2A7ABA83AE');
        $this->addSql('ALTER TABLE menu_items CHANGE description description TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE menu_items ADD CONSTRAINT `menu_items_menu_category_id_foreign` FOREIGN KEY (menu_category_id) REFERENCES menu_categories (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE menu_item_addons DROP FOREIGN KEY FK_35604DB49AB44FE0');
        $this->addSql('ALTER TABLE menu_item_addons ADD CONSTRAINT `menu_item_addons_menu_item_id_foreign` FOREIGN KEY (menu_item_id) REFERENCES menu_items (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE menu_item_variants DROP FOREIGN KEY FK_7956CEBC9AB44FE0');
        $this->addSql('ALTER TABLE menu_item_variants ADD CONSTRAINT `menu_item_variants_menu_item_id_foreign` FOREIGN KEY (menu_item_id) REFERENCES menu_items (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE messages DROP FOREIGN KEY FK_DB021E969AC0396');
        $this->addSql('ALTER TABLE messages DROP FOREIGN KEY FK_DB021E962A98155E');
        $this->addSql('ALTER TABLE messages CHANGE body body TEXT NOT NULL');
        $this->addSql('ALTER TABLE messages ADD CONSTRAINT `messages_conversation_id_foreign` FOREIGN KEY (conversation_id) REFERENCES conversations (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE messages ADD CONSTRAINT `messages_sender_user_id_foreign` FOREIGN KEY (sender_user_id) REFERENCES users (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE notifications DROP FOREIGN KEY FK_6000B0D3A76ED395');
        $this->addSql('ALTER TABLE notifications CHANGE body body TEXT NOT NULL');
        $this->addSql('ALTER TABLE notifications ADD CONSTRAINT `notifications_user_id_foreign` FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE orders DROP FOREIGN KEY FK_E52FFDEE9395C3F3');
        $this->addSql('ALTER TABLE orders DROP FOREIGN KEY FK_E52FFDEEB1E7706E');
        $this->addSql('ALTER TABLE orders DROP FOREIGN KEY FK_E52FFDEEFF881F6');
        $this->addSql('ALTER TABLE orders CHANGE status status ENUM(\'placed\', \'accepted\', \'preparing\', \'ready\', \'finding_rider\', \'rider_assigned\', \'at_restaurant\', \'picked_up\', \'on_the_way\', \'arrived\', \'delivered\', \'rejected_by_restaurant\', \'cancelled_by_customer\', \'cancelled_by_restaurant\', \'cancelled_no_rider\', \'cancelled_by_admin\', \'failed_delivery\') DEFAULT \'placed\' NOT NULL, CHANGE payment_method payment_method ENUM(\'cod\', \'gcash\', \'card\') NOT NULL, CHANGE customer_notes customer_notes TEXT DEFAULT NULL, CHANGE rejection_reason rejection_reason TEXT DEFAULT NULL, CHANGE cancellation_reason cancellation_reason TEXT DEFAULT NULL, CHANGE cancelled_by cancelled_by ENUM(\'customer\', \'restaurant\', \'rider\', \'admin\', \'system\') DEFAULT NULL');
        $this->addSql('ALTER TABLE orders ADD CONSTRAINT `orders_customer_id_foreign` FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE orders ADD CONSTRAINT `orders_restaurant_id_foreign` FOREIGN KEY (restaurant_id) REFERENCES restaurants (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE orders ADD CONSTRAINT `orders_rider_id_foreign` FOREIGN KEY (rider_id) REFERENCES riders (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE order_items DROP FOREIGN KEY FK_62809DB08D9F6D38');
        $this->addSql('ALTER TABLE order_items CHANGE special_instructions special_instructions TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE order_items ADD CONSTRAINT `order_items_order_id_foreign` FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE order_item_addons DROP FOREIGN KEY FK_462E2C7EE415FB15');
        $this->addSql('ALTER TABLE order_item_addons ADD CONSTRAINT `order_item_addons_order_item_id_foreign` FOREIGN KEY (order_item_id) REFERENCES order_items (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE order_reports DROP FOREIGN KEY FK_7650E0E8D9F6D38');
        $this->addSql('ALTER TABLE order_reports DROP FOREIGN KEY FK_7650E0EB79DEF28');
        $this->addSql('ALTER TABLE order_reports CHANGE against against ENUM(\'restaurant\', \'rider\', \'customer\', \'platform\') NOT NULL, CHANGE type type ENUM(\'missing_item\', \'wrong_item\', \'late_delivery\', \'no_show_rider\', \'rude_behavior\', \'customer_unreachable\', \'accident\', \'other\') NOT NULL, CHANGE description description TEXT NOT NULL, CHANGE status status ENUM(\'open\', \'under_review\', \'resolved\', \'rejected\') DEFAULT \'open\' NOT NULL, CHANGE resolution resolution TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE order_reports ADD CONSTRAINT `order_reports_order_id_foreign` FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE order_reports ADD CONSTRAINT `order_reports_reported_by_user_id_foreign` FOREIGN KEY (reported_by_user_id) REFERENCES users (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE order_status_history DROP FOREIGN KEY FK_471AD77E8D9F6D38');
        $this->addSql('ALTER TABLE order_status_history CHANGE changed_by changed_by ENUM(\'customer\', \'restaurant\', \'rider\', \'admin\', \'system\') NOT NULL, CHANGE note note TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE order_status_history ADD CONSTRAINT `order_status_history_order_id_foreign` FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE payments DROP FOREIGN KEY FK_65D29B328D9F6D38');
        $this->addSql('ALTER TABLE payments CHANGE method method ENUM(\'cod\', \'gcash\', \'card\') NOT NULL, CHANGE status status ENUM(\'pending\', \'paid\', \'refunded\', \'partially_refunded\', \'failed\') DEFAULT \'pending\' NOT NULL');
        $this->addSql('ALTER TABLE payments ADD CONSTRAINT `payments_order_id_foreign` FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE payment_status_history DROP FOREIGN KEY FK_CA42BDCA4C3A3BB');
        $this->addSql('ALTER TABLE payment_status_history CHANGE from_status from_status ENUM(\'pending\', \'paid\', \'refunded\', \'partially_refunded\', \'failed\') DEFAULT NULL, CHANGE to_status to_status ENUM(\'pending\', \'paid\', \'refunded\', \'partially_refunded\', \'failed\') NOT NULL, CHANGE changed_by changed_by ENUM(\'customer\', \'rider\', \'admin\', \'system\') NOT NULL, CHANGE note note TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE payment_status_history ADD CONSTRAINT `payment_status_history_payment_id_foreign` FOREIGN KEY (payment_id) REFERENCES payments (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE restaurants DROP FOREIGN KEY FK_AD837724A76ED395');
        $this->addSql('ALTER TABLE restaurants CHANGE description description TEXT DEFAULT NULL, CHANGE approval_status approval_status ENUM(\'pending\', \'approved\', \'rejected\') DEFAULT \'pending\' NOT NULL, CHANGE rejection_reason rejection_reason TEXT DEFAULT NULL, CHANGE operating_status operating_status ENUM(\'open\', \'closed\', \'temporarily_closed\') DEFAULT \'closed\' NOT NULL, CHANGE payout_method payout_method ENUM(\'bank\', \'ewallet\') DEFAULT NULL');
        $this->addSql('ALTER TABLE restaurants ADD CONSTRAINT `restaurants_user_id_foreign` FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE');
        $this->addSql('DROP INDEX restaurant_documents_restaurant_type_unique ON restaurant_documents');
        $this->addSql('ALTER TABLE restaurant_documents CHANGE type type ENUM(\'business_permit\', \'food_safety_permit\', \'owner_id\') NOT NULL, CHANGE status status ENUM(\'pending\', \'verified\', \'rejected\') DEFAULT \'pending\' NOT NULL, CHANGE rejection_reason rejection_reason TEXT DEFAULT NULL');
        $this->addSql('DROP INDEX restaurant_operating_hours_restaurant_day_unique ON restaurant_operating_hours');
        $this->addSql('ALTER TABLE restaurant_operating_hours CHANGE day_of_week day_of_week TINYINT NOT NULL');
        $this->addSql('ALTER TABLE restaurant_payouts DROP FOREIGN KEY FK_3F05DCFBB1E7706E');
        $this->addSql('ALTER TABLE restaurant_payouts CHANGE status status ENUM(\'pending\', \'paid\') DEFAULT \'pending\' NOT NULL');
        $this->addSql('ALTER TABLE restaurant_payouts ADD CONSTRAINT `restaurant_payouts_restaurant_id_foreign` FOREIGN KEY (restaurant_id) REFERENCES restaurants (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE restaurant_reviews DROP FOREIGN KEY FK_A33BB77A8D9F6D38');
        $this->addSql('ALTER TABLE restaurant_reviews DROP FOREIGN KEY FK_A33BB77A9395C3F3');
        $this->addSql('ALTER TABLE restaurant_reviews DROP FOREIGN KEY FK_A33BB77AB1E7706E');
        $this->addSql('ALTER TABLE restaurant_reviews CHANGE rating rating TINYINT NOT NULL, CHANGE comment comment TEXT DEFAULT NULL, CHANGE restaurant_reply restaurant_reply TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE restaurant_reviews ADD CONSTRAINT `restaurant_reviews_customer_id_foreign` FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE restaurant_reviews ADD CONSTRAINT `restaurant_reviews_order_id_foreign` FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE restaurant_reviews ADD CONSTRAINT `restaurant_reviews_restaurant_id_foreign` FOREIGN KEY (restaurant_id) REFERENCES restaurants (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE riders DROP FOREIGN KEY FK_4D574A38A76ED395');
        $this->addSql('ALTER TABLE riders CHANGE vehicle_type vehicle_type ENUM(\'motorcycle\', \'bicycle\', \'car\') NOT NULL, CHANGE approval_status approval_status ENUM(\'pending\', \'approved\', \'rejected\') DEFAULT \'pending\' NOT NULL, CHANGE rejection_reason rejection_reason TEXT DEFAULT NULL, CHANGE availability_status availability_status ENUM(\'offline\', \'available\', \'busy\') DEFAULT \'offline\' NOT NULL, CHANGE payout_method payout_method ENUM(\'bank\', \'ewallet\') DEFAULT NULL');
        $this->addSql('ALTER TABLE riders ADD CONSTRAINT `riders_user_id_foreign` FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE rider_cash_remittances DROP FOREIGN KEY FK_38E5F645FF881F6');
        $this->addSql('ALTER TABLE rider_cash_remittances CHANGE status status ENUM(\'pending\', \'confirmed\') DEFAULT \'pending\' NOT NULL');
        $this->addSql('ALTER TABLE rider_cash_remittances ADD CONSTRAINT `rider_cash_remittances_rider_id_foreign` FOREIGN KEY (rider_id) REFERENCES riders (id) ON DELETE CASCADE');
        $this->addSql('DROP INDEX rider_documents_rider_type_unique ON rider_documents');
        $this->addSql('ALTER TABLE rider_documents CHANGE type type ENUM(\'drivers_license\', \'vehicle_registration\', \'valid_id\', \'police_clearance\') NOT NULL, CHANGE status status ENUM(\'pending\', \'verified\', \'rejected\') DEFAULT \'pending\' NOT NULL, CHANGE rejection_reason rejection_reason TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE rider_earnings DROP FOREIGN KEY FK_34A967BBFF881F6');
        $this->addSql('ALTER TABLE rider_earnings DROP FOREIGN KEY FK_34A967BB8D9F6D38');
        $this->addSql('ALTER TABLE rider_earnings ADD CONSTRAINT `rider_earnings_order_id_foreign` FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE rider_earnings ADD CONSTRAINT `rider_earnings_rider_id_foreign` FOREIGN KEY (rider_id) REFERENCES riders (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE rider_payouts DROP FOREIGN KEY FK_8D95A693FF881F6');
        $this->addSql('ALTER TABLE rider_payouts CHANGE status status ENUM(\'pending\', \'paid\') DEFAULT \'pending\' NOT NULL');
        $this->addSql('ALTER TABLE rider_payouts ADD CONSTRAINT `rider_payouts_rider_id_foreign` FOREIGN KEY (rider_id) REFERENCES riders (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE rider_pool_declines DROP FOREIGN KEY FK_9A48C6358D9F6D38');
        $this->addSql('ALTER TABLE rider_pool_declines DROP FOREIGN KEY FK_9A48C635FF881F6');
        $this->addSql('DROP INDEX rider_pool_declines_order_rider_unique ON rider_pool_declines');
        $this->addSql('ALTER TABLE rider_pool_declines CHANGE action action ENUM(\'skipped\', \'expired\') NOT NULL');
        $this->addSql('ALTER TABLE rider_pool_declines ADD CONSTRAINT `rider_pool_declines_order_id_foreign` FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE rider_pool_declines ADD CONSTRAINT `rider_pool_declines_rider_id_foreign` FOREIGN KEY (rider_id) REFERENCES riders (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE rider_pool_offers CHANGE escalation_stage escalation_stage ENUM(\'initial\', \'widened\', \'incentivized\', \'admin_alerted\', \'customer_notified\', \'auto_cancelled\') DEFAULT \'initial\' NOT NULL');
        $this->addSql('ALTER TABLE rider_reviews DROP FOREIGN KEY FK_11ABCD128D9F6D38');
        $this->addSql('ALTER TABLE rider_reviews DROP FOREIGN KEY FK_11ABCD129395C3F3');
        $this->addSql('ALTER TABLE rider_reviews DROP FOREIGN KEY FK_11ABCD12FF881F6');
        $this->addSql('ALTER TABLE rider_reviews CHANGE rating rating TINYINT NOT NULL, CHANGE comment comment TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE rider_reviews ADD CONSTRAINT `rider_reviews_customer_id_foreign` FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE rider_reviews ADD CONSTRAINT `rider_reviews_order_id_foreign` FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE rider_reviews ADD CONSTRAINT `rider_reviews_rider_id_foreign` FOREIGN KEY (rider_id) REFERENCES riders (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE support_tickets DROP FOREIGN KEY FK_E9739508A76ED395');
        $this->addSql('ALTER TABLE support_tickets CHANGE message message TEXT NOT NULL, CHANGE status status ENUM(\'open\', \'in_progress\', \'closed\') DEFAULT \'open\' NOT NULL');
        $this->addSql('ALTER TABLE support_tickets ADD CONSTRAINT `support_tickets_user_id_foreign` FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE users CHANGE two_factor_secret two_factor_secret TEXT DEFAULT NULL, CHANGE two_factor_recovery_codes two_factor_recovery_codes TEXT DEFAULT NULL, CHANGE role role ENUM(\'admin\', \'restaurant\', \'rider\', \'customer\') NOT NULL, CHANGE status status ENUM(\'active\', \'suspended\', \'banned\') DEFAULT \'active\' NOT NULL');
        $this->addSql('ALTER TABLE vouchers DROP FOREIGN KEY FK_93150748B1E7706E');
        $this->addSql('ALTER TABLE vouchers CHANGE scope scope ENUM(\'platform\', \'restaurant\') NOT NULL, CHANGE type type ENUM(\'percentage\', \'fixed\', \'free_delivery\') NOT NULL');
        $this->addSql('ALTER TABLE vouchers ADD CONSTRAINT `vouchers_restaurant_id_foreign` FOREIGN KEY (restaurant_id) REFERENCES restaurants (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE voucher_redemptions DROP FOREIGN KEY FK_6D711ECB28AA1B6F');
        $this->addSql('ALTER TABLE voucher_redemptions DROP FOREIGN KEY FK_6D711ECB8D9F6D38');
        $this->addSql('ALTER TABLE voucher_redemptions DROP FOREIGN KEY FK_6D711ECB9395C3F3');
        $this->addSql('ALTER TABLE voucher_redemptions ADD CONSTRAINT `voucher_redemptions_customer_id_foreign` FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE voucher_redemptions ADD CONSTRAINT `voucher_redemptions_order_id_foreign` FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE voucher_redemptions ADD CONSTRAINT `voucher_redemptions_voucher_id_foreign` FOREIGN KEY (voucher_id) REFERENCES vouchers (id) ON DELETE CASCADE');
    }
}
